name: CI

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm i

      - name: Test and coverage
        run: npm run test -- --coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

      - name: Build
        run: npm run build
